import GreedyUniformity.Model

#check Fintype.card_perm
#check Equiv.swap
#check Equiv.swap_apply_def
#check Equiv.swap_apply_left
#check Equiv.swap_apply_right
#check Equiv.mul_apply
#check Equiv.trans_apply
#check Equiv.apply_symm_apply
#check Equiv.symm_apply_apply
#check finSumFinEquiv
#check Finset.sum_fiberwise_of_maps_to
#check Finset.sum_fiberwise_eq_sum_filter
#check Finset.filter_card_eq
#check Finset.card_filter_eq_iff
#check Finset.card_pos
#check Finset.card_pos.mpr
#check Finset.nonempty_iff_ne_empty
#check SimpleGraph.IsTree
#check SimpleGraph.IsTree.exists_vert_degree_one_of_nontrivial
#check SimpleGraph.Walk.exists_isPath_forall_isPath_length_le_length
#check SimpleGraph.IsAcyclic.eq_snd_of_adj_start
#check SimpleGraph.IsAcyclic.eq_penultimate_of_adj_end
#check SimpleGraph.Walk.cons
#check SimpleGraph.Walk.concat
#check SimpleGraph.Walk.tail
#check SimpleGraph.Walk.drop
#check SimpleGraph.Walk.take
#check SimpleGraph.Walk.snd
#check SimpleGraph.Walk.penultimate
#check SimpleGraph.Walk.support
#check SimpleGraph.Walk.length_cons
#check SimpleGraph.Walk.length_concat
#check SimpleGraph.Walk.IsPath.cons
#check SimpleGraph.Walk.IsPath.concat
#check SimpleGraph.Iso
#check SimpleGraph.Iso.mk
#check SimpleGraph.map
#check SimpleGraph.comap
#check Fintype.equivFin
#check Fintype.equivOfCardEq
#check Fintype.card_congr
#check Finset.finSumEquivOfFinset
